### PR TITLE
fix: Put the image loading logic in a non-blocking thread

### LINKED ISSUE #315: fix: put the image loading in another thread for listings/reviews
When  retrieving the listings/reviews, it could be better to put the retrieving for the images in another thread in order to see the rest of the page faster

### PR DESCRIPTION
**Pull request by Matboegli**
## Summary
This PR just put the image retrieving process in a non-blocking thread when retrieving a listing or a review. It does not change the `ViewReviewByResidency` file because we'll remove images from the review cards.

This closes #315.

### CODE REVIEW

File: app/src/main/java/com/android/mySwissDorm/ui/overview/BrowseCityViewModel.kt [hunk 1]
```diff
@@ -312,27 +312,36 @@ class BrowseCityViewModel(
...
-                      try {
-                        photoRepositoryCloud.retrievePhoto(fileName).image
-                      } catch (_: NoSuchElementException) {
-                        Log.e("BrowseCityViewModel", "Failed to retrieve the photo $fileName")
-                        null
-                      }
-                    }
-                listingCardUI = listingCardUI.copy(image = loadedImages)
-              }
-              listingCardUI
```
Comment (ghassanbaroudi) [inline app/src/main/java/com/android/mySwissDorm/ui/overview/BrowseCityViewModel.kt]: OK.
