### PR TITLE
fix: Implement the changes for cities

### LINKED ISSUE #175: Fix hard coded ressource id for homepage cities

### PR DESCRIPTION
**Pull request by Matboegli**
## Summary
This PR modify the admin page according to the changes in #225 concerning the cities. The `ImageId` field has been removed and an `AddPhotoButton` has been added with an `ImageGrid` and a full screen mode to visualize the city's image.

In addition to those changes, some shared constants has been moved to dedicated objects.

## Image Grid
In order to have better preview of a city image in the Homepage, the `ImageGrid`'s image dimensions can be specified for both height and width now.

This closes #175 and #224.

image

### CODE REVIEW

File: app/src/main/java/com/android/mySwissDorm/ui/photo/ImageGrid.kt [hunk 1]
```diff
@@ -45,35 +46,39 @@ fun ImageGrid(
     onImageClick: (Uri) -> Unit = {},
     onRemove: (Uri) -> Unit = {},
     modifier: Modifier = Modifier,
-    imageSize: Dp = 120.dp
+    imageWidth: Dp = 120.dp,
+    imageHeight: Dp = 120.dp,
```
Comment (rami-mallah) [inline app/src/main/java/com/android/mySwissDorm/ui/photo/ImageGrid.kt]: Good addition

**Review by rami-mallah — COMMENTED** [review]
Thanks for the fix, it works good.
- You changed the id into an actual image.
- The added flexibility to the `ImageGrid` (width and height) is a good idea

My only concern is that you still use some fixed sizes in the new UI. Will you change that in a future PR, since this task is assigned to you?
