### PR TITLE
fix: Move `blockedUserIds` into `UserInfo`

### LINKED ISSUE #286: Fix the blocked users not saved inside the profile of the user
This meant that when we block someone and then modify something in our profile, the blocked users disappear.

### PR DESCRIPTION
**Pull request by rami-mallah**
## Summary
This PR aims to store the `blockedUsersIds` directly inside the `UserInfo` which is inside the `Profile`, since it was done directly into Firebase before that. This caused that when we edited anything in the profile, it would remove all blocked users. This closes #286.

### Model Updates
- Added `blockedUserIds: List<String>` to `UserInfo` data class
- Updated `ProfileEntity` to include `blockedUserIds` and handle conversion to/from `Profile`
- Updated `AppDatabase` migration to include `blockedUserIds` column in profiles table

### Repository Updates
- Updated `ProfileRepositoryFirestore` to read/write `blockedUserIds` from `UserInfo` instead of direct Firestore access
- Modified `getBlockedUserIds()`, `addBlockedUser()`, and `removeBlockedUser()` to work with the nested structure

### Test Updates
- Updated unit tests (`ProfileEntityTest`, `ProfileDaoTest`) to include `blockedUserIds` in test data
- Refactored all `blocked_implementation` tests to use repository methods instead of manual Firestore deserialization
- Removed direct Firestore `FieldValue.arrayUnion/arrayRemove` operations from tests

### CODE REVIEW

File: app/src/main/java/com/android/mySwissDorm/model/profile/ProfileRepositoryFirestore.kt [hunk 1]
```diff
@@ -37,22 +36,24 @@ class ProfileRepositoryFirestore(private val db: FirebaseFirestore) : ProfileRep
   }
 
   override suspend fun getBlockedUserIds(ownerId: String): List<String> {
-    val doc = db.collection(PROFILE_COLLECTION_PATH).document(ownerId).get().await()
-    @Suppress("UNCHECKED_CAST") return doc.get("blockedUserIds") as? List<String> ?: emptyList()
+    val profile = getProfile(ownerId)
+    return profile.userInfo.blockedUserIds
```
Comment (sophieur444) [inline app/src/main/java/com/android/mySwissDorm/model/profile/ProfileRepositoryFirestore.kt]: getBlockedUserIds now calls getProfile. Please make sure getProfile returns an empty blocked list if the profile doc is missing, so callers don’t get exceptions.

**Review by sophieur444 — CHANGES_REQUESTED** [review]
Overall the pr is good! You followed the same structure that the group did for the fix of the bookmark bug where after editing the profile they resetted themselves, now it is included on the profile data that does not disappear. The code is clear and compact, good work! just maybe some small changes I wrote on the lines of code
