### PR TITLE
fix(backend): force user to add image to listing

### LINKED ISSUE #282: Fix: force the user to add an image to listings

### PR DESCRIPTION
**Pull request by ghassanbaroudi**
In this PR, I make sure the user is forced to upload at least one photo to their listing, so that displaying the listings is done in a uniform and clean manner. 
I also ensure that when editing a listing, if all images are removed, the edited listing cannot be saved and requires at least one image.

The tests for these specifications have been written with AI
This closes #282

### CODE REVIEW

File: app/src/androidTest/java/com/android/mySwissDorm/end2end/Epic2Test.kt
Comment (karlyounes) [inline app/src/androidTest/java/com/android/mySwissDorm/end2end/Epic2Test.kt]: Good documentation

File: app/src/main/java/com/android/mySwissDorm/ui/listing/EditListingViewModel.kt [hunk 1]
```diff
@@ -34,6 +34,11 @@ class EditListingViewModel(
         photoRepositoryLocal = photoRepositoryLocal,
         photoRepositoryCloud = photoRepositoryCloud) {
 
+  init {
+    // For Edit, require at least one photo before allowing the user to save changes
+    _uiState.value = _uiState.value.copy(requireAtLeastOnePhoto = true)
+  }
+
```
Comment (karlyounes) [inline app/src/main/java/com/android/mySwissDorm/ui/listing/EditListingViewModel.kt]: Smart change
