### PR TITLE
fix: store blocked user names locally for offline

### LINKED ISSUE #321: Fix blocked users not displayed when offline

### PR DESCRIPTION
**Pull request by rami-mallah**
> Disclaimer: This PR has only 250 lines of new logic, the rest being mostly tests, and a bit of new documentation added

## Problem

When viewing blocked users in the Settings screen, the app calls `getProfile()` for each blocked user to fetch their display name. This fails when offline, preventing users from seeing who they've blocked.

## Solution

Store blocked user display names locally in the database alongside the blocked user IDs. This enables offline access to blocked user names without requiring network calls.
This closes #321.

### Database Layer

- Added a new `blockedUserNames` field to `ProfileEntity` that stores a `Map<String, String>` mapping blocked user IDs to their display names. This is a local-only field that is not synced to the remote database. 
- Created a TypeConverter for `Map<String, String>` that converts between Kotlin maps and SQLite TEXT columns using a URL encoded pipe-delimited format to handle special characters safely. (I first didn't do that, but an AI helped handle that and proposed to me the URL encoded way)
- Added database migration 4 to 5 that adds the `blockedUserNames TEXT NOT NULL DEFAULT ''` column to the `profiles` table.

### Repository Layer

- Updated `ProfileRepositoryLocal` to store display names when adding blocked users via the new `addBlockedUserWithName()` method, and to remove stored names when unblocking. 
- Updated `ProfileRepositoryHybrid.addBlockedUser()` to fetch the target user's profile when online, construct their display name from `name` and `lastName`, and pass it to the local repository for storage. The method also ensures the local profile exists before attempting to add a blocked user. 
- Added `getBlockedUserNames()` method to the `ProfileRepository` interface and implemented it in all three repository implementations.

### UI Layer

Updated `SettingsViewModel.refresh()` to use stored names from local storage first, which works offline. If a name isn't stored for a blocked user, it falls back to fetching from remote (if online).

## Tests
Added unit tests to test new field storage locally.

## Notes
- All documentation and comments were generated with the help of AI
- URL-encoder usage was proposed by AI
- This PR description was restructured using AI to make it clearer

### CODE REVIEW

File: app/src/main/java/com/android/mySwissDorm/model/database/Converters.kt [hunk 1]
```diff
@@ -94,4 +94,55 @@ class Converters {
...
+   * characters (:, |, etc.)
+   *
+   * @param value The map to convert, or null.
+   * @return A string representation of the map, or null if the input was null or empty.
+   */
+  @TypeConverter
+  fun fromStringMap(value: Map<String, String>?): String {
+    if (value.isNullOrEmpty()) return ""
+    return value.entries.joinToString("|") {
+      "${java.net.URLEncoder.encode(it.key, "UTF-8")}:${java.net.URLEncoder.encode(it.value, "UTF-8")}"
```
Comment (ghassanbaroudi) [inline app/src/main/java/com/android/mySwissDorm/model/database/Converters.kt]: OK

File: app/src/main/java/com/android/mySwissDorm/model/database/Converters.kt [hunk 2]
```diff
@@ -94,4 +94,55 @@ class Converters {
...
+              } else {
+                null
+              }
+            }
+            .toMap()
+      } catch (e: Exception) {
+        emptyMap() // Return empty map on parsing error
+      }
+    }
+  }
```
Comment (ghassanbaroudi) [inline app/src/main/java/com/android/mySwissDorm/model/database/Converters.kt]: This is good, but if we have duplicated keys, I assume the map structure would only keep the last key right? I know the mapping is from uids to names (uids should be unique), but do you think there is a case where the map structure keeping only the last of the duplicated keys could cause an issue?

File: app/src/main/java/com/android/mySwissDorm/model/profile/ProfileRepositoryHybrid.kt [hunk 3]
```diff
@@ -276,22 +366,91 @@ class ProfileRepositoryHybrid(
...
+    }
+
+    // Offline and no local data
+    return emptyList()
+  }
+
+  /** Gets bookmarked listing IDs for other users (remote-only). */
+  private suspend fun getOtherUserBookmarkedListingIds(ownerId: String): List<String> {
+    if (!NetworkUtils.isNetworkAvailable(context)) {
+      return emptyList() // Can't fetch other users' data offline
```
Comment (ghassanbaroudi) [inline app/src/main/java/com/android/mySwissDorm/model/profile/ProfileRepositoryHybrid.kt]: LGTM

File: app/src/main/java/com/android/mySwissDorm/model/profile/ProfileRepositoryLocal.kt [hunk 4]
```diff
@@ -152,6 +152,32 @@ class ProfileRepositoryLocal(private val profileDao: ProfileDao, private val aut
...
+                "ProfileRepositoryLocal: Profile not found. Cannot get blocked user names for non-existent profile.")
+
+    require(entity.ownerId == ownerId) {
+      "ProfileRepositoryLocal: Cannot get blocked user names for profile with ownerId $ownerId. " +
+          "Only the current user's profile (${entity.ownerId}) is stored locally."
+    }
+
+    return entity.blockedUserNames
+  }
+
```
Comment (ghassanbaroudi) [inline app/src/main/java/com/android/mySwissDorm/model/profile/ProfileRepositoryLocal.kt]: OK

File: app/src/main/java/com/android/mySwissDorm/ui/settings/SettingsViewModel.kt [hunk 5]
```diff
@@ -87,19 +87,35 @@ class SettingsViewModel(
...
+                          if (displayName.isNotBlank()) {
+                            BlockedContact(uid = blockedUid, displayName = displayName)
+                          } else {
+                            // Fallback: use UID if no name available
+                            BlockedContact(uid = blockedUid, displayName = blockedUid)
+                          }
+                        }
+                        .getOrNull()
+                  }
                 }
```
Comment (ghassanbaroudi) [inline app/src/main/java/com/android/mySwissDorm/ui/settings/SettingsViewModel.kt]: OK

**Review by ghassanbaroudi — COMMENTED** [review]
The work is good, thanks for implementing this. If you could just clarify some points under my 2 questions it would be helpful as I didn't quite understand that part

**Review by ghassanbaroudi — APPROVED** [review]
Ok thanks for clarifying.
