### PR TITLE
fix: make anonymous name not clickable again

### LINKED ISSUE #326: Fix anonymous clickable in reviews
The "Anonymous" text was mistakenly made clickable, it shouldn't be.

### PR DESCRIPTION
**Pull request by rami-mallah**
## Problem
The "Anonymous" text was mistakenly made clickable in a recent PR. This PR fixes that. It closes #326.
This PR also solves a problem the last merge introduced. Since it added some fake `ProfileRepository`, and that this one had some new functions to implement, it made some errors that the automatic merge can't see. So this PR also adds those functions.

## Tests
Added tests and changed some old ones to ensure this behavior.
Comments were added by AI to make tests clearer.

### CODE REVIEW

File: app/src/androidTest/java/com/android/mySwissDorm/ui/review/ViewReviewScreenTest.kt
Comment (karlyounes) [inline app/src/androidTest/java/com/android/mySwissDorm/ui/review/ViewReviewScreenTest.kt]: Tests here look alright. Strong waiting times added and pretty good documentation. Good jobb

File: app/src/main/java/com/android/mySwissDorm/ui/review/ViewReviewScreen.kt [hunk 1]
```diff
@@ -186,18 +186,16 @@ fun ViewReviewScreen(
...
-                                        context.getString(R.string.profile_offline_message),
-                                        Toast.LENGTH_SHORT)
-                                    .show()
-                              }
-                            })
+                            Modifier.testTag(C.ViewReviewTags.POSTED_BY_NAME)
+                                .then(
+                                    // Only make clickable if review is not anonymous AND (online OR
+                                    // owner)
+                                    if (!review.isAnonymous &&
```
Comment (karlyounes) [inline app/src/main/java/com/android/mySwissDorm/ui/review/ViewReviewScreen.kt]: This fixes the issue we had good job!!
