### PR TITLE
fix(ui): fix translate button to appear only if needed

### LINKED ISSUE #333: Fix: remove the "translate" button if the listing/review doesn't need or can't be translated
If the app is in French, and that a listing/review is also in French, the "Translate" button shouldn't appear. Same thing if it is untranslatable.

### PR DESCRIPTION
**Pull request by anreymon**
### Summary

Previously, the "Translate" button appeared on every listings and on every reviews, even on the ones that are already in the same language as the app. This PR fixes this by displaying the "Translate" button only if the listing/review can be translated in the app's language. For instance, if the app is in French and a listing in also in French, the "Translate" button won't appear. The button also won't appear if the language couldn't be identified. Some tests were also added to verify that the fix works.

It closes #333

### CODE REVIEW

File: app/src/main/java/com/android/mySwissDorm/ui/listing/ViewListingScreen.kt [hunk 1]
```diff
@@ -113,6 +114,15 @@ fun ViewListingScreen(
 
   LaunchedEffect(listing) { viewListingViewModel.translateListing(context) }
 
+  LaunchedEffect(listingUIState.translatedDescription) {
+    showTranslateButton =
+        if (listingUIState.translatedDescription == "") {
+          false
+        } else {
```
Comment (karlyounes) [inline app/src/main/java/com/android/mySwissDorm/ui/listing/ViewListingScreen.kt]: I dont think the "" case is necessary since the "" will be translated to "". So the description will be equal to the translated one which causes the conditon below to be false either way. My statement is correct only if "" is translated to "" and I'm not sure about it.

**Review by karlyounes — APPROVED** [review]
The changes seem very good. Please just read the comments I said in ViewReview and ViewListing screens. I'm not sure about the statements I said so tell me if my way of thinking was wrong

**Review by karlyounes — APPROVED** [review]
The changes are now good. Well done :)
